let products = [
    {
      "id": 1001,
      "title": "Math",
      "description": "London",
      "price": 100,
      "image": "images/math.jpg",
      "availableInventory": 5,
      "slots": 5,
    },
    {
        "id": 1002,
        "title": "English",
        "description": "New York",
        "price": 150,
        "image": "images/english.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1003,
        "title": "Biology",
        "description": "Italy",
        "price": 75,
        "image": "images/biology.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1004,
        "title": "Chemistry",
        "description": "Russia",
        "price": 200,
        "image": "images/chemistry.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1005,
        "title": "Drama",
        "description": "Australia",
        "price": 85,
        "image": "images/drama.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1006,
        "title": "Piano",
        "description": "Germany",
        "price": 350,
        "image": "images/piano.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1007,
        "title": "Football",
        "description": "Spain",
        "price": 80,
        "image": "images/football.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1008,
        "title": "Physics",
        "description": "Bulgaria",
        "price": 215,
        "image": "images/physics.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1009,
        "title": "Maltese",
        "description": "Malta",
        "price": 150,
        "image": "images/maltese.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
      {
        "id": 1010,
        "title": "Animation",
        "description": "Sweden",
        "price": 325,
        "image": "images/animation.jpg",
        "availableInventory": 5,
        "slots": 5,
      },
]